<?php $_productCollection=$this->getLoadedProductCollection(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="product-pager"><?php echo $this->getToolbarHtml() ?></div>
    <hr style="margin-top: 0px;">
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; ?>
    <?php foreach ($_productCollection as $_product): ?>
        <div class="col-sm-3 col-md-3">
            <?php $product = $_product->load($_product->getProductId()); ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ">
                <img src="<?php echo  Mage::getBaseUrl('media') . 'catalog/product/'.$product->getImage();?>" />
            </a>
            
        </div>
        <div class="col-sm-9 col-md-9">
            <h3><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>
            <?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php endif; ?>
            
            <p>
            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
            </p>
            <?php //echo $this->getPriceHtml($_product, true) ?>
            
            <div class="actions">
                <?php if($_product->isSaleable()): ?>
                    <!--<button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn btn-danger success btn-cart btn" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>-->
                <a title="<?php echo $this->__('View Details') ?>" class="button_link btn btn-success" href="<?php echo $_product->getProductUrl() ?>"><strong><?php echo $this->__('View Details') ?></strong></a>
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <hr>
    <?php endforeach ?>
<?php endif; ?>
        
