<footer id="footer" style="margin:0">

  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="copyright col-xs-12 col-sm-3 col-md-3">
		  Copyright © 2015 - Habitos Saludables de Mexico S de RL de CV
		</div>
		
        <div class="phone col-xs-6 col-sm-3 col-md-3">
          <div class="footer-icon">
			<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" enable-background="new 0 0 16 16" xml:space="preserve">
			  <path fill="#c6c6c6" d="M11.001,0H5C3.896,0,3,0.896,3,2c0,0.273,0,11.727,0,12c0,1.104,0.896,2,2,2h6c1.104,0,2-0.896,2-2
			   c0-0.273,0-11.727,0-12C13.001,0.896,12.105,0,11.001,0z M8,15c-0.552,0-1-0.447-1-1s0.448-1,1-1s1,0.447,1,1S8.553,15,8,15z
				M11.001,12H5V2h6V12z"></path>
			</svg>
		  </div>
          <strong class="title">Llame al:</strong> (664) 448-0863 
          
        </div>
		
        <div class="col-sm-4 col-md-4">
<ul>
<li><a href="http://www.habitossaludables.com.mx/mx/privacy-policy" hidefocus="true" style="outline: none;">Politica de Privacidad</a></li>
<li class="last privacy"><a href="http://www.habitossaludables.com.mx/mx/terms-and-conditions" hidefocus="true" style="outline: none;">Terminos y condiciones</a></li>
</ul>
        </div>
		
        <div class="col-xs-12 col-sm-2 col-md-2">
          <a href="#" class="up">
			<span class="glyphicon glyphicon-arrow-up"></span>
		  </a>
        </div>
      </div>
    </div>
  </div><!-- .footer-bottom -->
</footer>
<div class="clearfix"></div>
