<div class="banner-set load">
    <div class="container">
        <div class="banners">

            <a class="banner" href="{{store url='productos/cafe/cafe-negro.html'}}">
                <img src="{{media url="wysiwyg/img/cafenegro-menu.jpg"}}" alt="" width="253" height="158" />
                <h2 class="title"><strong>Caf&eacute; Negro</strong></h2>
                <div class="description">Es la combinaci&oacute;n perfecta de caf&eacute; Colombiano e Indonesio con un aroma exuberante que le deleitar&aacute;.</div>
            </a>

            <a class="banner" href="{{store url='productos/cafe/cafe-espumoso.html'}}">
                <img src="{{media url="wysiwyg/img/espumoso-menu.jpg"}}" alt="" width="253" height="158" />
                <h2 class="title"><strong>Caf&eacute; Espumoso</strong></h2>
                <div class="description">Exquisito sabor que ademas nos brinda vitalidad y energ&iacute;a para cada momento de nuestro d&iacute;a.</div>
            </a>

            <a class="banner" href="{{store url='productos/cafe/cafe-con-leche.html'}}">
                <img src="{{media url="wysiwyg/img/cafeconleche-menu.jpg"}}" alt="" width="253" height="158" />
                <h2 class="title"><strong>Caf&eacute; con Leche</strong></h2>
                <div class="description">Caf&eacute; con Leche Gourmet Enriquecido nos ayuda a tener un m&aacute;ximo de energ&iacute;a gracias a los extractos de nuestros ingredientes.</div>
            </a>

            <a class="banner" href="{{store url='productos/te/te-chai.html'}}">
                <img src="{{media url="wysiwyg/img/teverde-menu.jpg"}}"}}" alt="" width="253" height="158" />
                <h2 class="title"><strong>T&eacute; Chai</strong></h2>
                <div class="description">Produce un efecto templado y balsamico, actua como reparador natural de la digesti&oacute;n y da una maravillosa sensaci&oacute;n de bienestar.</div>
            </a>

            <a class="banner" href="{{store url='productos/te/te-hs.html'}}">
                <img src="{{media url="wysiwyg/img/tehs-menu1.jpg"}}" alt="" width="253" height="158" />
                <h2 class="title"><strong>T&eacute; HS</strong></h2>
                <div class="description">La f&oacute;rmula de T&eacute; Hs fue creada para limpiar delicadamente el tracto digestivo, desintoxicar su cuerpo y purificar la sangre.</div>
            </a>

        </div>
        <div class="clearfix"></div>
    </div>

    <div class="nav-box">
        <div class="container">
            <a class="prev" href="#"><span class="glyphicon glyphicon-arrow-left"></span></a>
            <div class="pagination switches"></div>
            <a class="next" href="#"><span class="glyphicon glyphicon-arrow-right"></span></a>	
        </div>
    </div>
</div>