<div class="slider rs-slider load">
    <div class="tp-banner-container">
        <div class="tp-banner">
            <ul style="background:#000">
                <li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
                    <div class="elements">
                        <div class="tp-caption lfl skewtoleft start" 
                            data-x="30"
                            data-y="10"
                            data-customin=""
                            data-customout=""
                            data-speed="1500"
                            data-start="500"
                            data-easing="Back.easeInOut"
                            data-endspeed="400"
                            data-endeasing="Power1.easeIn">
                            <img src="{{media url="wysiwyg/slideshow/usa-mexico-map.png"}}">
                        </div>
                        <div class="tp-caption lfl skewtoleft start" 
                            data-x="600"
                            data-y="40"
                            data-customin=""
                            data-customout=""
                            data-speed="1000"
                            data-start="900"
                            data-easing="Back.easeInOut"
                            data-endspeed="400"
                            data-endeasing="Power1.easeIn">
                            <img src="{{media url="wysiwyg/slideshow/taza.png"}}">
                        </div>
                        <div class="tp-caption lfr skewtoright start"
			  data-x="560"
			  data-y="82"
			  data-speed="1500"
			  data-start="1000"
			  data-easing="Power4.easeOut"
			  data-endspeed="1000"
			  data-endeasing="Power1.easeIn">
			  <img src="{{media url="wysiwyg/slideshow/ahoraenmexico.png"}}">
			</div>
                    </div>
                    
                    <img src="{{media url="wysiwyg/slideshow/background.jpg"}}" alt="" data-bgfit="cover" data-bgposition="left center" data-bgrepeat="no-repeat">

                </li>
                <li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
                    <div class="elements">
                        <div class="tp-caption lfl skewtoleft start" data-x="30"
                            data-y="10"
                            data-customin=""
                            data-customout=""
                            data-speed="1500"
                            data-start="500"
                            data-easing="Back.easeInOut"
                            data-endspeed="400"
                            data-endeasing="Power1.easeIn">
                            <img src="{{media url="wysiwyg/slideshow/usa-mexico-map.png"}}">
                        </div>




<div class="tp-caption lfl skewtoleft start" data-x="600"
            data-y="40"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="900"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn">
            <img src="{{media url="wysiwyg/slideshow/taza.png"}}">
            </div>
            

<div class="tp-caption lfr skewtoright start"
			  data-x="560"
			  data-y="82"
			  data-speed="1500"
			  data-start="1000"
			  data-easing="Power4.easeOut"
			  data-endspeed="1000"
			  data-endeasing="Power1.easeIn">
			  <img src="{{media url="wysiwyg/slideshow/ahoraenmexico.png"}}">
			</div>
			
			
		  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/background-opcion2.jpg"}}" alt="" data-bgfit="cover" data-bgposition="left center" data-bgrepeat="no-repeat">
		</li>
                


<li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
		  <div class="elements">
			
			

			<div class="tp-caption customin customout description col-xs-5"
			  data-x="240"
			  data-y="20"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="1500"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn">
			  <img src="{{media url="wysiwyg/slideshow/masdelicioso.png"}}">
			</div>



<div class="tp-caption lfl skewtoleft start" data-x="40"
            data-y="140"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="1500"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn">
            <img src="{{media url="wysiwyg/slideshow/productos.png"}}">
            </div>
                  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/background2.jpg"}}" alt="" data-bgfit="cover" data-bgposition="left center" data-bgrepeat="no-repeat">
		</li>
        
        		
		<li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
		  <div class="elements">


            <div class="tp-caption lfl skewtoleft start" data-x="0"
            data-y="60"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="1500"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn">
            <img src="{{media url="wysiwyg/slideshow/ingredientes.png"}}">
            </div>
			

			
		  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/background3.jpg"}}" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat">
		</li>



<li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
		  <div class="elements">


            <div class="tp-caption lfr skewtoright start" data-x="0"
            data-y="60"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="1500"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn"
              >
            <img src="{{media url="wysiwyg/slideshow/cafeconleche.png"}}">
            </div>
			

			
		  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/background4.jpg"}}" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat">
		</li>		
		


<li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
		  <div class="elements">


            <div class="tp-caption lfr skewtoright start" data-x="450"
            data-y="120"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="1000"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn"
              >
            <img src="{{media url="wysiwyg/slideshow/cafenegro.png"}}">
            </div>
			
            
            <div class="tp-caption lfl skewtoleft start" data-x="900"
            data-y="120"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="800"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn"
              >
            <img src="{{media url="wysiwyg/slideshow/cafe-negro-bolsa.png"}}">
            </div>

			
		  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/background5.jpg"}}" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat">
		</li>
        

		<li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
		  <div class="elements">


            <div class="tp-caption lfr skewtoright start" data-x="80"
            data-y="120"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="500"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn"
              >
            <img src="{{media url="wysiwyg/slideshow/techai.png"}}">
            </div>
			

			
		  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/background6.jpg"}}" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat">
		</li>
        

<li data-delay="8000" data-transition="fade" data-slotamount="7" data-masterspeed="2000">
		  <div class="elements">


            <div class="tp-caption lfr skewtoright start" data-x="380"
            data-y="100"
			  data-customin=""
			  data-customout=""
			  data-speed="1000"
			  data-start="500"
			  data-easing="Back.easeInOut"
			  data-endspeed="400"
			  data-endeasing="Power1.easeIn"
              >
            <img src="{{media url="wysiwyg/slideshow/tehs-titulo.png"}}">
            </div>
			

			
		  </div>
		  
		  <img src="{{media url="wysiwyg/slideshow/tehs-background.jpg"}}" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat">
		</li>
                        		
		
	  </ul>
	  <div class="tp-bannertimer"></div>
	</div>
  </div>
</div>

<div class="clearfix"></div>