<?php $items = json_encode(Mage::registry('items')); ?>
<?php $flag = Mage::registry('flag'); ?>

<div class="dashboard row">
    <div class="col-sm-12 col-md-12">
        <div class="page-title page-head">
            <h4 class="title"><?php echo $this->__('Affiliate Network') ?>: 
                <?php 
                switch ($flag) {
                    case 1:
                        echo "Patrocinados";
                        break;
                    case 2:
                        echo "Directos";
                        break;
                    case 3:
                        echo "Frontales Directos";
                        break;
                    default:
                        break;
                }
                ?></h4>
        </div>
        
        <div class="box-account">            
            <div class="col-md-12 col-sm-12" style="text-align: center;">
                <a class="btn" href="?item=1"><?php echo "Frontales" ?></a>                 
                <a class="btn" href="?item=2"><?php echo "Directos" ?></a>
                <a class="btn" href="?item=3"><?php echo "Frontales Directos" ?></a>
                <!--<a class="btn" href="?item=4"><?php echo "Clientes Preferentes" ?></a>-->
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="box-account box-recent account-box ad-orders" style="margin-top:15px;">
            <div class="col-sm-3 col-md-3 pull-right" style="text-align: right; height: 50px; font-size: 13px;">
                <div class="checkbox"> 
                    <label><input type="checkbox" name="fit" value="1" checked> Vista de árbol</label>
                </div>
            </div>
            <div id="basicdiagram" style="width: auto; min-height: 550px; border-width: 1px;" class="hidden-xs"></div>
        </div> 
    </div>
</div>

<script>
    var items = <?php echo $items ?>;
</script>