<?php 
$referral_edit = Mage::getSingleton('affiliate/affiliatecustomers')->load(Mage::getSingleton('customer/session')->getCustomer()->getId());
$status =$referral_edit->getStatus(); 
if($status == MW_Affiliate_Model_Statusreferral::LOCKED){?>
<p class="error-msg">
<?php echo $this->__('Affiliate Account was disabled, please contact us to solve this problem.') ?>						
</p>
<?php } else {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $name = $customer->getName();

    $affiliate_customer = Mage::getModel('affiliate/affiliatecustomers')->load($customer->getId());
    $credit_customer = Mage::getModel('credit/creditcustomer')->load($customer->getId());
    $payment_gateway = $affiliate_customer->getPaymentGateway();
    
    $host = parse_url(Mage::getBaseUrl());
    $custom_url = Mage::getStoreConfig('affiliate/invitation/custom_member_url') ? 
            Mage::getStoreConfig('affiliate/invitation/custom_member_url1').$affiliate_customer->getCustomerUrl() : 
            $host['scheme'].'://'.$host['host'].'/miembro/'.$affiliate_customer->getCustomerUrl();
    
    $affiliate_network = $affiliate_customer->getAnetwork() ? $affiliate_customer->getAnetwork() : 1;
    $payment_email = $affiliate_customer->getPaymentEmail();
    $referral_code = $affiliate_customer->getReferralCode();
    $auto_withdrawn = $affiliate_customer->getAutoWithdrawn();
    $withdrawn_level = $affiliate_customer->getWithdrawnLevel();
    $reserve_level = $affiliate_customer->getReserveLevel();
    $bank_name = $affiliate_customer->getBankName();
    $name_account = $affiliate_customer->getNameAccount();
    $bank_country = $affiliate_customer->getBankCountry();
    $swift_bic = $affiliate_customer->getSwiftBic();
    $account_number = $affiliate_customer->getAccountNumber();
    $re_account_number = $affiliate_customer->getReAccountNumber();
    $referral_site = $affiliate_customer->getReferralSite();
    $balance = $credit_customer->getCredit();?>
<div id="tabajax">	  
<form action="<?php echo $this->getUrl('affiliate/index/referral') ?>" method="post" name="mw_referral_account" id="form-validate" >
<div class="row dashboard affilate">
    <div class="col-sm-12 col-md-12">
    	<h4 class="titile"><?php echo $this->__('My Account Info') ?></h4>
    
        <div class="account-box ad-account-info box-account box-info form-box">
<!--            <div class="withdrawal-config">
                <span class="amount" style="font-size:16px;font-weight:bold">
                    <?php echo $this->__('Current Balance') ?>:
                    <span id="your_balance" class="price">
                        <?php echo Mage::helper('core')->currency($balance,true,false);?>
                    </span>
                </span>	
                <span class="pull-right">
                    <a href="<?php echo Mage::getUrl('credit/index/index')?>"><?php echo $this->__('View History') ?></a>		    	
                    1Check Affiliate Withdrawal config
                    <?php if(Mage::getStoreConfig('affiliate/money/enable_withdrawal')){?>
                    <?php 
                    $withdrawnType = Mage::getModel('affiliate/affiliatecustomers')->load($customer->getId())->getAutoWithdrawn();

                    //If withdrawn type is manual
                    if(intval($withdrawnType) == MW_Affiliate_Model_Autowithdrawn::MANUAL) { ?>
                            <span> | </span>
                                    <a href="<?php echo Mage::getUrl('affiliate/index/withdrawn')?>"><?php echo $this->__('Request Withdrawn') ?></a>			    			
                    <?php } else if(intval($withdrawnType) == MW_Affiliate_Model_Autowithdrawn::AUTO) { ?>
                            <p>
                                    <span class="note_withdrawn">
                                            <?php echo $this->__('*Auto payment when account balance reaches '), '<b>', Mage::helper('core')->currency($withdrawn_level,true,false), '</b>'; ?>
                                    </span>
                            </p>			
                    <?php }?>

                    <?php }	?>
                    1Check Affiliate Withdrawal config
                </span>
            </div>
                    <hr>-->
            
		
            <div class="">
                <!--<h5 class="legend"><?php echo $this->__('My Account Info') ?></h5>-->
                <table class="table">
                    <tbody>
                    <tr>
                        <td><label for="name"><?php echo $this->__('Affiliate Name') ?>:</label></td>
                        <td> <span id="name" style="font-size:14px"><?php echo $name;?></span></td>
                    </tr>
                    <tr>
                        <td><label for="referral_code"><?php echo $this->__('Referral Code') ?>:</label></td>
                        <td><span id="name" style="font-size:14px"><?php echo $referral_code;?></span></td>
                    </tr>
                    <tr>
                        <td><label for="name"><?php echo $this->__('Affiliate Custom URL') ?>:</label></td>
                        <td> <?php if (strlen($custom_url)>0): ?><a href="<?php echo $custom_url;?>" target="_blank"><span style="font-size:14px"><?php echo $custom_url;?></span></a> | <?php endif; ?> <a class="" href="<?php echo Mage::getUrl('affiliate/index/url')?>" style="margin-left:5px"><?php echo $this->__('Edit') ?></a></td>
                    </tr>
                    </tbody>
                </table>
                <!--2Check Affiliate Withdrawal config-->
                <?php if(Mage::getStoreConfig('affiliate/money/enable_withdrawal')){?>
                <p>
                    <label for="getway_withdrawn"><em>*</em><?php echo $this->__('Payment Method') ?></label>
	            <select id="getway_withdrawn" name="getway_withdrawn" class="required-entry form-control">
                        <option value=""><?php echo $this->__('Please select a payment method') ?></option>
                        <?php $gateways = unserialize(Mage::helper('affiliate/data')->getGatewayStore());?>
                        <?php foreach ($gateways as $gateway): ?>
                            <?php if(strtolower(trim($gateway['mw_status'])) == 'yes'):?>
                                <option <?php if($payment_gateway == $gateway['gateway_value']) echo 'selected="selected"'?> value="<?php echo $gateway['gateway_value'];?>"><?php echo $gateway['gateway_title'];?></option>
                            <?php endif; ?>
                        <?php endforeach;?>
                    </select>    
                </p>
                <p>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Withdrawal Notification Email') ?></label>
	            <input type="text" name="paypal_email" id="paypal_email" value="<?php echo $payment_email;?>"title="<?php echo $this->__('Paypal Email') ?>" class="form-control input-text validate-email required-entry" />
                </p> 
                <ul id="form_account_bank">
	                <li class="fields">
	                     <div class="field">
							<label for="bank_name" class="required"><em>*</em><?php echo $this->__('Bank Name') ?></label>
		                    <div class="input-box">
		                        <input type="text" name="bank_name" id="bank_name" value="<?php echo $bank_name;?>" title="<?php echo $this->__('Bank Name') ?>" class="input-text required-entry" />
		                    
		                    </div>
					    </div>
	                    <div class="field">
							<label for="name_account" class="required"><em>*</em><?php echo $this->__('Name on account') ?></label>
		                    <div class="input-box">
		                        <input type="text" name="name_account" id="name_account" value="<?php echo $name_account;?>" title="<?php echo $this->__('Name on account') ?>" class="input-text required-entry" />
		                    </div>
					    </div>
	                </li>
	                <li class="fields">
	                     <div class="field">
							<label for="bank_country" class="required"><em>*</em><?php echo $this->__('Bank Country') ?></label>
		                    <div class="input-box">
		                    	<!--  <input type="text" name="bank_country" id="bank_country" value="<?php //echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php //echo $this->__('Bank Country') ?>" class="input-text required-entry"/>-->
		                    	<?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($bank_country,'bank_country','bank_country','Bank Country') ?>
		                    </div>
					    </div>
	                    <div class="field">
							<label for="swift_bic" class="required"><em>*</em><?php echo $this->__('SWIFT code') ?></label>
		                    <div class="input-box">
		                        <input type="text" name="swift_bic" id="swift_bic" value="<?php echo $swift_bic;?>" title="<?php echo $this->__('SWIFT code') ?>" class="input-text required-entry" />
		                    
		                    </div>
					    </div>
	                </li>
	                <li class="fields">
	                     <div class="field">
							<label for="account_number" class="required"><em>*</em><?php echo $this->__('Account Number') ?></label>
		                    <div class="input-box">
		                        <input type="text" name="account_number" id="account_number" value="<?php echo $account_number;?>" title="<?php echo $this->__('Account Number') ?>" class="input-text required-entry" />
		                    
		                    </div>
					    </div>
					    <div class="field">
							<label for="re_account_number" class="required"><em>*</em><?php echo $this->__('Re-enter Account Number') ?></label>
		                    <div class="input-box">
		                        <input type="text" name="re_account_number" id="re_account_number" value="<?php echo $re_account_number;?>" title="<?php echo $this->__('Re-enter Account Number') ?>" class="input-text required-entry validate-re_account_number" />
		                    
		                    </div>
					    </div>
					</li>
				</ul>
                <p>
                    <label for="auto_withdrawn" class="required"><em>*</em><?php echo $this->__('Auto Withdrawal') ?></label>
	            <select id="auto_withdrawn" name="auto_withdrawn" class="form-control">
                        <?php $autowithdrawns = MW_Affiliate_Model_Autowithdrawn::getOptionArray();?>
                        <?php foreach ($autowithdrawns as $value=>$autowithdrawn):?>
                            <option <?php if($auto_withdrawn == $value) echo 'selected="selected"'?> value="<?php echo $value;?>"><?php echo $autowithdrawn;?></option>
                        <?php endforeach;?>
                    </select>
                </p>
                <p>	                   
                    <?php $store_id = Mage::app()->getStore()->getId();?>
                    <?php $max = Mage::helper('affiliate/data')->getWithdrawMaxStore($store_id);?>
                    <?php $min = Mage::helper('affiliate/data')->getWithdrawMinStore($store_id);?>
                    <label for="payment_release_level" class="required"><em>*</em><?php echo $this->__('Auto payment when account balance reaches (%s - %s)',Mage::helper('core')->currency($min),Mage::helper('core')->currency($max))?></label>
                    <input type="text" name="payment_release_level" id="payment_release_level" value="<?php echo round($withdrawn_level,0);?>" title="<?php echo $this->__('Auto payment when account balance reaches') ?>" class="form-control input-text validate-digits required-entry" />				
                </p>
                <p>
                    <label for="reserve_level" ><?php echo $this->__('Reserve Level') ?><br /><?php echo $this->__('(to be kept in account)') ?></label>
                    <input type="text" name="reserve_level" id="reserve_level" value="<?php echo round($reserve_level,0);?>"title="<?php echo $this->__('Reserve Level') ?>" class="form-control input-text validate-digits" />
                </p>
            <?php } ?>
				<!--2Check Affiliate Withdrawal config-->
	    <br />
            <!--<p><label class="page-title" for="note_affiliate" ><?php echo $this->__('* Note: Affiliate may use balance as store credit in shopping cart.') ?></label></p>-->
        </div>
		
<!--        <div class="buttons-set">   	
            <button type="submit" title="<?php echo $this->__('Save') ?>" id="referral_acount" class="button_link btn"><span><span><?php echo $this->__('Save') ?></span></span></button>
        </div>		  -->
    </div>
</div>
</div>
</form>
</div>
<!--3Check Affiliate Withdrawal config-->
<?php if(Mage::getStoreConfig('affiliate/money/enable_withdrawal')){?>
<script type="text/javascript">
	var dataForm = new VarienForm('form-validate', true);
	
	if($('auto_withdrawn').value=='2')
    {
    	$('payment_release_level_').hide(); 
    }
	else
    {
    	$('payment_release_level_').show();
    };
	if($('getway_withdrawn').value=='banktransfer')
    {
    	$('form_account_bank').show();
    	$('mw_paypal_email').hide(); 
    	
    }
	else if($('getway_withdrawn').value=='check'){
    	$('form_account_bank').hide(); 
    	$('mw_paypal_email').hide();
    }
    else
    {
    	$('mw_paypal_email').show(); 
    	$('form_account_bank').hide();
    };
    $('auto_withdrawn').observe('change', function () {		
            if($('auto_withdrawn').value=='2')
            {
            	$('payment_release_level_').hide(); 
            }
            else
            {
            	$('payment_release_level_').show();
            }
			 
	});
	$('getway_withdrawn').observe('change', function () {	
		if($('getway_withdrawn').value=='banktransfer')
        {
        	$('form_account_bank').show(); 
        	$('mw_paypal_email').hide();
        }
		else if($('getway_withdrawn').value=='check'){
        	$('form_account_bank').hide(); 
        	$('mw_paypal_email').hide();
        }
        else
        {
        	$('mw_paypal_email').show();
        	$('form_account_bank').hide();
        }
			 
	});

</script>
<?php } ?>
<!--3Check Affiliate Withdrawal config-->
<?php }?>



<?php if ($affiliate_network ==1):?>
<style>
    .left-navigation ul li:nth-child(2){
        display: none;
    }
</style>
<?php elseif ($affiliate_network ==2): ?>
<style>
.left-navigation ul li:nth-child(3), .left-navigation ul li:nth-child(4){
        display: none;
    }
</style>    
<?php endif; ?>
