<div class="row dashboard">
    <div class="col-sm-12 col-md-12">
        <div class="page-title title-buttons">
            <h4 class="title"><?php echo $this->__('Address Book') ?></h4>
            <!--<button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button btn" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>-->
        </div>
        <div class="addresses-list">
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>    
            <div class="col-sm-6 col-md-6 addresses-primary">
                <div class="form-box">
                    <h4 class="title"><?php echo $this->__('Default Addresses') ?></h4>                    
                    <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>                       
                        <h5 class="title"><?php echo $this->__('Default Billing Address') ?></h5>
                        <address>
                            <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                        </address>
                        <p><a class="btn" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>                       
                        <hr>
                    <?php else: ?>                        
                        <h4 class="title"><?php echo $this->__('Default Billing Address') ?></h4>
                        <?php echo $this->__('You have no default billing address in your address book.') ?>
                        <hr>
                    <?php endif ?>

                    <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>                        
                        <h5 class="title"><?php echo $this->__('Default Shipping Address') ?></h5>
                        <address>
                            <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                        </address>
                        <p><a class="btn" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
                        
                    <?php else: ?>
                        <h5 class="title"><?php echo $this->__('Default Shipping Address') ?></h5>
                        <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
                    <?php endif ?>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 addresses-additional">
                <div class="form-box">
                    <h5 class="title"><?php echo $this->__('Additional Address Entries') ?></h5>                    
                    <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
                        <?php foreach($_pAddsses as $_address): ?>
                            <address>
                                <?php echo $this->getAddressHtml($_address) ?>
                            </address>
                    <p><a class="btn" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a></p>
                    <p><a href="#" class="btn link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a></p>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
                    <?php endif ?>
                </div>
            </div>
    </div>
        <div class="clearfix"></div>
        <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
    </div>
</div>
    <script type="text/javascript">
    //<![CDATA[
        function deleteAddress(addressId) {
            if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
                window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
            }
            return false;
        }
    //]]>
    </script>
    
