<div class="row dashboard">
    <div class="col-sm-12 col-md-12">
    <?php if($this->getTitle()): ?>
    <div class="page-title">
        <h4 class="title"><?php echo $this->getTitle() ?></h4>
    </div>
    <?php endif; ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" class="form-box">
    <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <h5 class="title"><?php echo $this->__('Contact Information') ?></h5>
        <?php echo $this->getNameBlockHtml() ?>

        <label for="company"><?php echo $this->__('Company') ?></label>
        <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
        <label for="telephone"><span class="required">*</span> <?php echo $this->__('Telephone') ?></label>
        <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="form-control input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
        <label for="fax"><?php echo $this->__('Fax') ?></label>
        <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                  
    </div>
    <div class="fieldset">
        <h5 class="title"><?php echo $this->__('Address') ?></h5>
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
        <label for="street_1"><span class="required">*</span> <?php echo $this->__('Street Address') ?></label>
        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="form-control input-text <?php echo $_streetValidationClass ?>" />
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="form-control input-text <?php echo $_streetValidationClass ?>" />
        <?php endfor; ?>
        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
            <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
            <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
        <?php endif; ?>
                
        <label for="city"><span class="required">*</span> <?php echo $this->__('City') ?></label>
        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                
        <span class="required">*</span> <strong><?php echo $this->__('State/Province') ?></strong>
        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="form-control validate-select" style="display:none;">
            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
        </select>
        <script type="text/javascript">
        //<![CDATA[
            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
        //]]>
        </script>
        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
        <label for="zip"><span class="required">*</span> <?php echo $this->__('Zip/Postal Code') ?></label>
        
        <input type="text" class="form-control" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
        <label for="country"><span class="required">*</span> <?php echo $this->__('Country') ?></label>
                    
        <?php echo $this->getCountryHtmlSelect() ?>
            
         <p class="required"><?php echo $this->__('* Required Fields') ?></p>
         
        
        <?php if($this->isDefaultBilling()): ?>
         <p><strong><?php echo $this->__('Default Billing Address') ?></strong></p>
        <?php elseif($this->canSetAsDefaultBilling()): ?>
            <p><input type="checkbox" style="float:left; margin-right: 5px; margin-top: 5px;" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label></p>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>
            
        <?php if($this->isDefaultShipping()): ?>
            <p><strong><?php echo $this->__('Default Shipping Address') ?></strong></p>
        <?php elseif($this->canSetAsDefaultShipping()): ?>
            <p><input type="checkbox" style="float:left; margin-right: 5px; margin-top: 5px;" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label></p>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1" />
        <?php endif; ?>
        
        
        <hr>
    </div>
    <div class="buttons-set">       
        <button data-action="save-customer-address" type="submit" title="<?php echo $this->__('Save Address') ?>" class="btn button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>
</form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    
    $('country').addClassName('form-control');
//]]>
</script>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
