<?php $affiliate = Mage::registry('collection');?>
<?php $customer_id = Mage::registry('id');?>
<?php $last = json_decode($affiliate['historic'])?>
<?php print_R($collection); ?>
<?php $entity = $last[0]->order; ?>
<?php $sale = Mage::getModel('sales/order')->getCollection()
    ->addAttributeToFilter('customer_id', array('in' => array($customer_id)))        
    ->addAttributeToFilter('affiliate_network', array('eq' => 2));
?>
<div class="main-col-inner">
    <div id="messages"></div>
    <div class="content-header">
        <h3 class="icon-head head-adminhtml-affiliatebonuspreferred"><?php echo $this->__('Expiracion de Recompra') ?>: 
            <?php echo Mage::getModel('customer/customer')->load($customer_id)->getName() ?>
        </h3>
                
        <p class="form-buttons">
            <button style="" onclick="setLocation('<?php echo Mage::helper('adminhtml')->getUrl("affiliate/adminhtml_affiliatebinary/expired") ?>')" class="scalable back" type="button" title="Volver"><span><span><span>Volver</span></span></span></button>
            <button style="" onclick="editForm.submit();" class="scalable save" type="button" title="Save Reference"><span><span><span><?php echo $this->__('Save') ?></span></span></span></button>
        </p>
    </div>
    <div class="entry-edit">  
        <form action="<?php echo Mage::helper("adminhtml")->getUrl('affiliate/adminhtml_affiliatebinary/saveexpired', array('id' => $customer_id)) ?>" class="form-horizontal" method="post" id="edit_form" enctype="multipart/form-data"> 
            <?php echo $this->getBlockHtml('formkey')?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $this->__('Date') ?></h4>
        </div>
        <div class="fieldset">
            <div class="main-stuff">  
                <h3><?php echo $this->__('Ultima Recompra') ?>:</h3> 
                <select name="recompra" class="form-control">
                    <?php foreach ($sale as $key => $order):?>
                    <?php $historial = Mage::getResourceModel('sales/order_status_history_collection')
                        ->addAttributeToFilter('main_table.status', array('eq'=>'complete'))
                        ->addAttributeToFilter('main_table.entity_name', array('in'=>array('invoice','shipment')))
                        ->addAttributeToFilter('main_table.parent_id', array('in'=>array($order->getEntityId())))
                        ->getFirstItem();    
                    ?>
                    <?php $expired = date("Y-m-d 23:59:59",strtotime($historial->getData('created_at'). ' +1 Month')); ?>
                    <?php $selected = $order->getEntityId() == $entity ? "selected" : ""?>
                    <?php $_ty;
                        switch ($order->getAffiliateSaleType()) {
                           case 0: $_ty = "No se toma en cuenta";break;
                           case 1: $_ty = "Recompra";break;
                           case 2: $_ty = "Paquete";break;
                           case 3: $_ty = "Constructor";break;
                            default: $_ty = "No se toma en cuenta"; break;
                        }?>
                        <option value="<?php echo $order->getEntityId()?>" <?php echo $selected?>>Fecha expiraci&oacute;n: <?php echo $expired. ' | No. de Orden: '.$order->getIncrementId().' | '.$_ty ?></option>                    
                    <?php endforeach;?>                    
                </select>
            </div>
        </div>
        <div class="clear"></div>    
        </form>
    </div>
</div>
<script type="text/javascript">
        editForm = new varienForm('edit_form', '');
    </script>
<style>
    .form-control {
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
    color: #555;
    display: block;
    font-size: 14px;
    height: 34px;
    line-height: 1.42857;
    padding: 6px 12px;
    transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
    width: 40%;
}

</style>