<div class="row dashboard">
    <div class="col-sm-12 col-md-12">
        <div class="page-title">
            <h4 class="title"><?php echo $this->__('Edit Account Information') ?></h4>
        </div>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" class="form-box" method="post" id="form-validate" autocomplete="off">
            <?php echo $this->getBlockHtml('formkey')?>
            <h4 class="title"><?php echo $this->__('Account Information') ?></h4>
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>

            <label for="email"><span class="required">*</span> <?php echo $this->__('Email Address') ?></label>
            <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="form-control input-text required-entry validate-email" />

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
            <?php endif ?>

            <input type="checkbox" style="float:left; margin-right: 5px; margin-top: 5px;" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>



            <div id="div_password" style="display: none;">
                <h4 class="title"><?php echo $this->__('Change Password') ?></h4>

                <label for="current_password"><span class="required">*</span> <?php echo $this->__('Current Password') ?></label>
                <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                <input type="text" class="form-control input-text no-display" name="dummy" id="dummy" />
                <input type="password" title="<?php echo $this->__('Current Password') ?>" class="form-control input-text" name="current_password" id="current_password" />


                <label for="password"><span class="required">*</span> <?php echo $this->__('New Password') ?></label>
                <input type="password" title="<?php echo $this->__('New Password') ?>" class="form-control input-text validate-password" name="password" id="password" />

                <label for="confirmation"><span class="required">*</span> <?php echo $this->__('Confirm New Password') ?></label>
                <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="form-control input-text validate-cpassword" name="confirmation" id="confirmation" />

            </div>
            <br>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <hr>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Save') ?>" class="btn button"><span><span><?php echo $this->__('Save') ?></span></span></button>
            </div>
        </form>
    </div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('div_password').show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('div_password').hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
</div>
<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>