<div class="row">
    <div class="col-sm-12 col-md-12" style="margin-top:0; padding-top:0">			
        <div class="row">
            <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form-box">
   
            <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
            <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>        
            <label for="email_address"><span class="required">*</span><?php echo $this->__('Email Address') ?></label>
            <input type="text" name="email" alt="email" id="email_address" class="form-control input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />    
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <div class="clearfix"></div>
            <div class="buttons-box clearfix">
                <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
                <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-default"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    
           </div><!-- .buttons-box -->
</form>
</div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
