<div class="row dashboard">
    <div class="col-sm-12 col-md-12">
        <div class="page-title">
            <h4 class="title"><?php echo $this->__('Newsletter Subscription') ?></h4>
        </div>
        <div class="form-box">
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <?php echo $this->getChildHtml('form_before')?>
            <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
                <div class="fieldset">
                    <?php echo $this->getBlockHtml('formkey')?>
                    <h5 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h5>                    
                    <input type="checkbox" style="float: left; margin-right: 5px; margin-top: 5px;" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>                    
                </div>
                <hr>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->__('Save') ?>" class="button btn"><span><span><?php echo $this->__('Save') ?></span></span></button>
                </div>
            </form>
        </div>
    </div>
</div>
<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>

<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
