<?php $_order = $this->getOrder(); ?>
<?php $_net = $_order->getAffiliateNetwork(); ?>
<?php $_type = $_order->getAffiliateSaleType() ? $_order->getAffiliateSaleType() : 0; ?>
<form action="<?php echo Mage::helper("adminhtml")->getUrl("affiliate/adminhtml_affiliateindex/savenetwork/order_id/".$_order->getId())?>" method="POST" id="getCFDI">
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
    <?php $network = array('1' => "Uninivel",'2' => "Binario")?>
    <?php $type = array("0" => "No se toma en cuenta", '1' => "Recompra", '2' => "Paquete", "3" => "Constructor", "4" => "Recompra y Paquete", "5" => "Recompra y Constructor", "6" => "Paquete y Bono", "7" => "Paquete, Constructor y Recompra")?>
    <div class="box-left">
        <!--Order Information-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo Mage::helper('affiliate')->__('Binary Information');?></h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('affiliate')->__('Network');?></label></td>
                            <td class="value">
                                <select name="affiliate_network">
                                    <?php foreach ($network as $key => $value): ?>
                                        <option value="<?php echo $key ?>" <?php echo $key == $_net ? "selected" : ""?>><?php echo $value?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('affiliate')->__('Tipo de Compra');?></label></td>
                            <td class="value">
                                <select name="affiliate_sale_type">
                                    <?php foreach ($type as $key => $value): ?>
                                        <option value="<?php echo $key ?>" <?php echo $key == $_type ? "selected" : ""?>><?php echo $value?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align: center;">
                                <br>
                                <button id="cfdi" class="scalable " type="submit" title="<?php echo Mage::helper('affiliate')->__('Save Order');?>" ><span><span><span><?php echo Mage::helper('affiliate')->__('Save Order'); ?></span></span></span></button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>