<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row dashboard">
    <div class="col-sm-12 col-md-12">
        <div class="page-title title-buttons">
            <h4 class="title"><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h4>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div style="text-align: center;"><?php echo $this->getChildHtml('buttons') ?></div>
            </div> <br> <br>
            <div class="order-info" style="text-align: center;">
                <?php $_links = $this->getLinks(); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php if($_link->getUrl()): ?>
                        <a class="btn" href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a>
                    <?php else: ?>
                        <a class="btn  btn-success"><?php echo $_link->getLabel() ?></a>
                    <?php endif; ?> 
                <?php endforeach; ?>
            </div> 
        </div>
        
        <p class="order-date" style="text-align: center;"><strong><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></strong></p>
        <div class="row">            
            <?php if (!$_order->getIsVirtual()): ?>
            <div class="order-info-box">
                <div class="col-md-6 col-sm-12 col-1">
                    <div class="box form-box">
                        <div class="box-title">
                            <h5><?php echo $this->__('Shipping Address') ?></h5>
                        </div>
                        <div class="box-content">
                            <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12  col-2">
                    <div class="box form-box">
                        <div class="box-title">
                            <h5><?php echo $this->__('Shipping Method') ?></h5>
                        </div>
                        <div class="box-content">
                            <?php if ($_order->getShippingDescription()): ?>
                                <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                            <?php else: ?>
                                <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <?php endif; ?>


            <div class="order-info-box">
                <div class="col-md-6 col-sm-12 col-1">
                    <div class="box form-box">
                        <div class="box-title">
                            <h5><?php echo $this->__('Billing Address') ?></h5>
                        </div>
                        <div class="box-content">
                            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-2">
                    <div class="box form-box box-payment">
                        <div class="box-title">
                            <h5><?php echo $this->__('Payment Method') ?></h5>
                        </div>
                        <div class="box-content">
                            <?php echo $this->getPaymentInfoHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
