<?php $_option = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>

<br>
<strong><?php echo $this->escapeHtml($_option->getTitle())?> *</strong>
<?php if (count($_selections) == 1 && $_option->getRequired()): ?>

    <?php echo $this->getSelectionQtyTitlePrice($_selections[0]) ?>
    <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>

<?php else:?>
    <ul class="include">
    <?php foreach($_selections as $_selection): ?>
        <li>
            <input onclick="bundle.changeSelection(this)" style="float:left; margin-right: 5px;" class="change-container-classname checkbox bundle-option-<?php echo $_option->getId() ?> <?php if ($_option->getRequired()) echo 'validate-one-required-by-name' ?>" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" type="checkbox" name="bundle_option[<?php echo $_option->getId() ?>][]"<?php if ($this->_isSelected($_selection)) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?> value="<?php echo $_selection->getSelectionId() ?>"/>
             <label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"> <?php echo $this->getSelectionQtyTitlePrice($_selection) ?></label>
        <?php if($_option->getRequired()): ?>
            <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
        <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
<?php endif; ?>

