<?php $oRequestToken = $this->getRequestToken(); ?>
<form id="form-validate" method="post" action="<?php echo $this->getUrl('affiliate/invitation/invite')?>">
    <div class="fieldset group-select">
        <h5 class="legend"><?php echo $this->__('Connect & Share');?></h5>
        <span><?php echo $this->__('With friends on Facebook, Twitter, or Google.') ?></span>
        
        
        <div class="customer-name">
            <?php $addonClass="";?>
            <?php if(version_compare(Mage::getVersion(),"1.3.2.4","<=")) $addonClass = " input-box";?>
            <div class="<?php echo $addonClass;?> name-firstname">
                <?php 
                $url_new = Mage::app()->getRequest()->getParam('mw_link');
                $url_protocol = Mage::app()->getRequest()->getParam('mw_pro');
                if($url_new && $url_protocol)
                {   
                    $url_news = $url_protocol.'//'.$url_new;
                    $url = Mage::helper('affiliate')->getLinkBanner(Mage::getModel('customer/session')->getCustomer(),$url_news);

                }
                else $url = Mage::helper('affiliate')->getLink(Mage::getModel('customer/session')->getCustomer());
                ?>
                <div style = "padding-top: 10px;">
                    <!-- AddThis Button BEGIN -->
                    <div class="addthis_toolbox addthis_default_style addthis_32x32_style"
                            addthis:url="<?php echo $url;?>"
                    addthis:title="<?php echo $url; ?>"
                    addthis:description="<?php echo $url; ?>">
                    <a class="addthis_button_preferred_1"></a>
                    <a class="addthis_button_preferred_2"></a>
                    <a class="addthis_button_preferred_3"></a>
                    <a class="addthis_button_preferred_4"></a>
                    <!--  <a class="addthis_button_compact"></a>-->
                    <a href="http://www.addthis.com/bookmark.php?v=250&pubid={YOUR_PROFILE_ID}" class="addthis_button_compact"></a> 
                    <a class="addthis_counter addthis_bubble_style"></a>
                    </div>
                    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-500a790c6c746380"></script>
                </div>
            </div>
        </div>            
    </div>
    <hr>
    <div class="fieldset group-select">
        <h5 class="legend"><?php echo $this->__('Referral Link');?></h5>
        <span><?php echo $this->__('Copy + paste your personal link into your website, blog, email or IM.') ?></span>
        <div class="customer-name">
            <?php $addonClass="";?>
            <?php if(version_compare(Mage::getVersion(),"1.3.2.4","<=")) $addonClass = " input-box";?>
            <div>
                <div class="div_share">
                    <input class="form-control" id="referral_link_input" type="text" name="url_link" value="<?php echo $url ?>"  readonly="readonly" style="width:100%" onclick="this.select()">
                    <div class="clear_both"><span> </span></div>						
                </div>
            </div>
        </div>
        
        <hr>
            
        <!-- <a id="referral_link_edit" href="#">Edit</a> -->
        <ul id="referral_link_edit_block" class="form-list">
            <li class="fields">
                <div>
                	<?php $addonClass="";?>
                	<?php if(version_compare(Mage::getVersion(),"1.3.2.4","<=")) {$addonClass = " input-box";}?>
				    <div>
						<div>
							<p><?php echo $this->__('Your custom link: ') ?></p>
							<input id="referral_link_custom" type="text" name="url_link_edit" value=""  style="width:100%">
							<div class="clear_both"><span></span></div>						
						</div>
				    </div>
				</div>
            </li>
            <li>
            	<a id="referral_link_update" href="#">Update</a>
            </li>
        </ul>
    </div>
    
    <div class="fieldset group-select">
        <h5 class="legend"><?php echo $this->__('Referral Code');?></h5>
        <span><?php echo $this->__('') ?></span>
        <div class="customer-name">
            <div>
                <div class="div_share">
                    <?php $customer_id = Mage::getModel('customer/session')->getCustomer()->getId();
                    if($customer_id){
                          $referral_code = Mage::getModel('affiliate/affiliatecustomers')->load($customer_id)->getReferralCode();
                          if($referral_code == '') Mage::helper('affiliate') ->setReferralCode($customer_id);
                    }
                    $referral_code = Mage::getModel('affiliate/affiliatecustomers')->load($customer_id)->getReferralCode();?>
                    <?php echo $this->__('Your referral code (manual): <b>%s</b>',$referral_code) ?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="fieldset group-select">
        <?php echo $this->getBlockHtml('formkey')?>
        <h5 class="legend"><?php echo $this->__('Invite Friends Via Email');?></h5>
        <span><?php echo $this->__('Send invitation emails to your friends and family');?></span>
        <div class="customer-name">
            <?php $addonClass="";?>
            <?php if(version_compare(Mage::getVersion(),"1.3.2.4","<=")) $addonClass = " input-box";?>
            <div class="field<?php echo $addonClass;?> name-firstname">
                <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('affiliate')->__('Email of your friends');?><em style="color:#EB340A">*</em></label>
                <textarea class="form-control input-text required-entry" title="Email" name="email" id="email" style="width:550px; height:70px"></textarea>
                    <?php 
                        //$url = Mage::getUrl('affiliate/invitation/widget');
                        //$url = substr($url,strpos($url,'/',7));
                    ?>
                        <!-- <a href="#" onclick="showPlaxoABChooser('email', '<?php //echo $url;?>'); return false"><img src="<?php //echo $this->getSkinUrl('mw_affiliate/images/add_button.gif')?>" alt="<?php //echo Mage::helper('affiliate')->__('Add from my address book');?>" /></a>-->
                    <!-- <a href="#" onClick="javascript:mw_popup_func();return false;"><img src="<?php //echo $this->getSkinUrl('mw_affiliate/images/add_button.gif')?>" alt="<?php //echo Mage::helper('affiliate')->__('Add from my address book');?>" /></a>  -->

                    <!-- Gmail contacts import btn -->
                <a href="javascript:void()" onclick="javascript:popup('https://www.google.com/accounts/OAuthAuthorizeToken?oauth_token=<?php echo $oRequestToken; ?>')" style="display:inline-block;margin-bottom:10px" class="btn btn-danger">Add from Google contacts</a>
                <div><?php echo $this->__('Separate with commas (,)');?></div>
                
                <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('affiliate')->__('Message');?><em style="color:#EB340A">*</em></label>
                <div class="input-box">
                    <textarea class="form-control input-text required-entry" title="Message" name="message" id="message" style="width:550px; height:200px"></textarea>
                </div>
            </div>
        </div>
        <p class="required"><?php echo Mage::helper('affiliate')->__("* Required Fields");?></p>
        <div>
            <button class="button_link btn form-button" title="<?php echo Mage::helper('affiliate')->__("Send");?>" type="submit"><span><span>  <?php echo Mage::helper('affiliate')->__("Send");?>  </span></span></button>
            
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function mw_popup_func(){
		var popWin =  window.open('<?php echo $this->getUrl('affiliate/invitation/loginmail');?>','newwindow','toolbar=no,location=no,menubar=no,titlebar=no,status=yes,width=500,height=500,resizable=no,scrollbars=yes,top=0,left=0');
	}
    //]]>

    function popup(url) {
    	window.open(url, 'gmailwindow','toolbar=no,location=no,menubar=no,titlebar=no,status=yes,width=800,height=600,resizable=no,scrollbars=yes,top=0,left=0');
    }

    document.observe('dom:loaded', function() {
        $('referral_link_edit_block').hide();
    });

    $('referral_link_edit').observe('click', function(Event) {
        Event.stop();
        $(this).hide();
        $('referral_link_edit_block').show();
    });

    $('referral_link_update').observe('click', function(Event) {
        Event.stop();
        $('referral_link_edit').show();
        $('referral_link_edit_block').hide();

        linkComponent = ($('referral_link_input').value).split('?');
        verifiedKey = linkComponent[1];
        $('referral_link_input').setValue($('referral_link_custom').value + '/?' + verifiedKey);
    });

</script>