<div class="row">
    <div class="col-sm-6 col-md-6 contact-info" style="margin-top:0; padding-top:0">			
        <div class="row">
            <h1><strong><?php echo $this->__('Login or Create an Account') ?></strong></h1>
            <h2><?php echo $this->__('New Customers') ?></h2>            
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>            
            <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
            
            <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button btn" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                
            <div class="clearfix"></div>
        </div>			
    </div>
    <div class="col-sm-6 col-md-6">
        <form id="login-form" action="<?php echo $this->getPostActionUrl() ?>" class="form-box register-form" method="POST">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <h2><?php echo $this->__('Registered Customers') ?></h2>
            <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
            <div id="success"></div>
            <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label>
            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="form-control input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                           
            <label for="pass" ><?php echo $this->__('Password') ?> <span class="required">*</span></label>
            <input type="password" name="login[password]" class="form-control input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
           
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p><a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a></p>
            <div class="clearfix"></div>
            <div class="buttons-box clearfix">
                <button type="submit" class="btn btn-default" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
           </div><!-- .buttons-box -->
        </form>
    </div>
</div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
